NAVBAR_TINT_COLOR = '#fff'.uicolor
NAVBAR_BUTTON_TINT_COLOR = '#e74c3c'.uicolor
NAVBAR_FONT = 'HelveticaNeue'.uifont(22)
NAVBAR_FONT_COLOR = '#E21818'.uicolor
MENU_BACKGROUND_COLOR = '#111'.uicolor
TOAST_BACKGROUND_COLOR = '#3498db'.uicolor
TOAST_TEXT_COLOR = '#fff'.uicolor
TOAST_FONT = 'HelveticaNeue-Light'.uifont(21)
FACEBOOK_PERMISSIONS = %w(email user_birthday publish_actions)
FIREBASE_URL = 'http://personaldiary.firebaseio.com'
SPINKIT_COLOR = '#3498db'.uicolor