EMERALD_COLOR = '#2ecc71'.uicolor
NEPHRITIS_COLOR = '#2cc36b'.uicolor
ALIZARIN_COLOR = '#e74c3c'.uicolor
PETER_RIVER_COLOR = '#55acee'.uicolor
NAVBAR_TINT_COLOR = '#2ecc71'.uicolor
NAVBAR_BUTTON_TINT_COLOR = '#fff'.uicolor
NAVBAR_FONT = 'HelveticaNeue'.uifont(22)
NAVBAR_FONT_COLOR = '#fff'.uicolor
MENU_BACKGROUND_COLOR = '#111'.uicolor
TOAST_BACKGROUND_COLOR = '#2ecc71'.uicolor
TOAST_TEXT_COLOR = '#fff'.uicolor
TOAST_FONT = 'HelveticaNeue-Light'.uifont(21)
FACEBOOK_PERMISSIONS = %w(email user_birthday publish_actions)
FIREBASE_URL = 'http://personaldiary.firebaseio.com'
SPINKIT_COLOR = '#2ecc71'.uicolor